### ISSUE TITLE
Support for Elasticsearch 2.2.0

### ISSUE THREAD

**Issue by dirkschneemann** [ngageoint/elasticgeo#13]
Hi,

I did not succeed building the extension for Elasticsearch 2.2.0 (the most recent stable one at the time of writing) which is in compliance with the current docs.

Are there any future plans to make this possible anytime soon?
Regards

**Comment by sjudeng** [comment]
We recently merged in a contribution that added support for 2.1 (see #12). With that, hopefully it should be much easier to add support for 2.2, but it will depend on what the breaking changes are. @joelstewart any thoughts?

**Comment by joelstewart** [comment]
Elasticsearch 2.2.0 includes a dependency change in Lucene version.  The Elasticgeo project sed Lucene's XGeoHashUtils the ElasticCompat2 class, the name in Lucene changed to GeoHashUtils.  So it compiles for me with that change...

but a test is failing, testPolygonLimitSplittedFilter with 2.2.0 .    I don't know what that is about.  I don't see anything listed in the elasticsearch breaking changes in 2.2.0 docs to say to expect any functional behaviors to change for geo.  So that is a mystery to me.

**Comment by sjudeng** [comment]
Thanks @joelstewart. There was a minor mapping update to resolve the test failure.

The current version compiles with passing unit tests against Elasticsearch 2.2.0. Once we get some miles under this I can make a release and get some pre-built binaries uploaded.

**Comment by sjudeng** [comment]
The release created today includes pre-compiled versions of the plugin for elasticsearch-2.2.0.

https://github.com/ngageoint/elasticgeo/releases/tag/2.8.1-RC1
